#-------------------------------
# General Site Settings
title: Sowoon
logo: logo.svg # You can add own logo.
description: Sowoon 블로그


#-------------------------------
# Author Settings
author:
  name: Jeon Jihoon (Sowoon)
  image: 01.jpg
  say-hello: <Strong>Sowoon 블로그</Strong>
  bio: 웹 개발 그리고 <a href="https://soundcloud.com/user-368654404">음악</a>

#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/sowoon_121 # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: sowoon # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: sowoon_121 # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
